# NumPy
- NumPy is the essential package for scientific computing in Pythong
- It introduces a new data structure class: N-dimensional Arrays (ndarray)

In [1]:
import numpy as np
# Let's make a multi-dimensional array by passing a list containing lists
x = np.array([[1,2,3],[4,5,6],[4,5,6]])
print(type(x))
print(x)

<class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]
 [4 5 6]]


In [5]:
# create a range of values
x = np.arange(15)
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [7]:
# create a range then reshare it into an ndarray
x = np.arange(15).reshape(3,5)
print(x)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [ ]:
ref. https://github.com/peterthorsteinson/Py_Jupyter/blob/master/07_NumPy.ipynb

print("\n1-D 4 int32")
a = np.array([1,2,3,4])
print(a)
print(a.shape)
print(a.ndim)
print(a.dtype.name)

print("\n2-D 2x3 float64")
b = np.array([(1.5,2,3), (4,5,6)])
print(b)
print(b.shape)
print(b.ndim)
print(b.dtype.name)

print("\n2-D 2x2 complex")
c = np.array( [ [1,2], [3,4] ], dtype=complex )
print(c)
print(c.shape)
print(c.ndim)
print(c.dtype.name)

print("\n2-D 3x4 float64 zeros")
d = np.zeros( (3,4) )
print(d)
print(d.shape)
print(d.ndim)
print(d.dtype.name)

print("\n3-D 2x3x4 float64 ones")
e = np.ones( (2,3,4), dtype=np.int16 )
print(e)
print(e.shape)
print(e.ndim)
print(e.dtype.name)

## Indexing and Slicing an ndarray

In [8]:
x = np.array([[1, 2, 3], [4, 5, 6]], np.int32) # 2-dimensional array of size 2 x 3, composed of 4-byte integer elements
print(x)

[[1 2 3]
 [4 5 6]]


In [9]:
print(x[1,2])

6

In [33]:
print(x[:,0:2])

[[1 2]
 [4 5]
 [4 5]]


In [34]:
s = np.arange(13)**2
print(s)

[  0   1   4   9  16  25  36  49  64  81 100 121 144]


In [36]:
print(s[0], s[4], s[:3])

0 16 [0 1 4]


In [37]:
print(s[-5:-2])

[ 64  81 100]


In [39]:
print(s[-5::2]) # 5th from last value til the last value. Hope 2 indexes forward at a time

[ 64 100 144]


In [40]:
print(s[-5::-2]) # 5th from last value til the last value. Hope 2 indexes backwards at a time

[64 36 16  4  0]


In [41]:
r = np.arange(36)
r.resize((6,6))
print(r)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]


In [42]:
# Get 3nd row, 5th col (0th column and row exist since this really just a list of lists + some formatting attributes)
print(r[2,4])

16


In [43]:
print(r[2][4]) #Same as ^

16


In [44]:
print(r[3, 3:6])

[21 22 23]


In [45]:
# Get all values over 30
print(r[r > 30])

[31 32 33 34 35]


In [46]:
# Write all values over 30 as 30
r[r > 30] = 30
print(r)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 30 30 30 30 30]]


In [47]:
r2 = r[:3,:3]
print(r2)

[[ 0  1  2]
 [ 6  7  8]
 [12 13 14]]


In [49]:
# Set all values of the array to 0
r2[:] = 0
print(r2)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [50]:
# If we look at the original R, we can see that the slice has been changed!
# If we do not want to change the original array we need to use copy()
# R2 is just a reference to r with no data stored in memory assigned to r2, so to change the data we had to change r
print(r)

[[ 0  0  0  3  4  5]
 [ 0  0  0  9 10 11]
 [ 0  0  0 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 30 30 30 30 30]]


In [51]:
r3 = r.copy()
print(r3)

[[ 0  0  0  3  4  5]
 [ 0  0  0  9 10 11]
 [ 0  0  0 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 30 30 30 30 30]]


## Iterate Over Arrays

In [53]:
# Let's create a 4x3 array with the random values between 0 and 9
test = np.random.randint(0,10,[4,3])
test

array([[1, 1, 2],
       [9, 2, 4],
       [7, 8, 1],
       [0, 8, 1]])

In [54]:
# Remember, an array is just a list containing lists. We can iterate as we would a list
for i in test:
    print(i)

[1 1 2]
[9 2 4]
[7 8 1]
[0 8 1]


In [56]:
for i in range(len(test)): # instead of range(len()) we can just use enumerate()
    print(test[i])

[1 1 2]
[9 2 4]
[7 8 1]
[0 8 1]


In [57]:
test2 = test**2
test2

array([[ 1,  1,  4],
       [81,  4, 16],
       [49, 64,  1],
       [ 0, 64,  1]], dtype=int32)

In [58]:
#Iterating through 2 arrays using zip()
for i, j in zip(test, test2):
    print(i, '+',j,'=',i+j)

[1 1 2] + [1 1 4] = [2 2 6]
[9 2 4] + [81  4 16] = [90  6 20]
[7 8 1] + [49 64  1] = [56 72  2]
[0 8 1] + [ 0 64  1] = [ 0 72  2]


## Broadcasting (Array Multiplication/Division)

- Broadcasting: The way numpy multiplies arrays of various shapes.

In [19]:
a = np.array([1.0, 2.0, 3.0])
b = np.array([2.0, 2.0, 2.0])
c = a * b
print(c)

[2. 4. 6.]


In [20]:
a = np.array([1.0, 2.0, 3.0])
b = np.array([2.0, 2.0, 2.0])
c = a * b
print(c)

[2. 4. 6.]


In [21]:
x = np.arange(4)
xx = x.reshape(4,1)
y = np.ones(5)
z = np.ones((3,4))
print(x)

[0 1 2 3]


In [22]:
print(xx)

[[0]
 [1]
 [2]
 [3]]


In [23]:
print(y)

[1. 1. 1. 1. 1.]


In [24]:
print(z)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [25]:
print(x + y)  # <type 'exceptions.ValueError'>: shape mismatch: objects cannot be broadcast to a single shape

ValueError: operands could not be broadcast together with shapes (4,) (5,) 

In [26]:
print(xx + y)
# Note: This is not consistent with matrix addition rules
# Two matrices may be added or subtracted only if they have the same dimension; 
# that is, they must have the same number of rows and columns. 

[[1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2.]
 [3. 3. 3. 3. 3.]
 [4. 4. 4. 4. 4.]]


In [27]:
print(x + z)

[[1. 2. 3. 4.]
 [1. 2. 3. 4.]
 [1. 2. 3. 4.]]


In [28]:
a = np.array([1.0, 2.0, 3.0])
b = np.array([4.0, 5.0, 6.0])
c = a * b
print(c)

[ 4. 10. 18.]


In [32]:
a = np.array([1.0, 2.0, 3.0])
b = np.array([4.0, 5.0, 6.0]).reshape(3,1)
c = a * b
print(c)

[[ 4.  8. 12.]
 [ 5. 10. 15.]
 [ 6. 12. 18.]]


## Transpose Arrays

In [27]:
z = np.array([[4,5,6], [16,25,37]]) # Notice when you input 2 arrays into an array function, it vstacks by default
print(z)

[[ 4  5  6]
 [16 25 37]]


In [28]:
print(z.shape)

(2, 3)


In [29]:
# Transpose an array (swap the rows and columns). We turn our array 90 degrees anticlockwise
z.T

array([[ 4, 16],
       [ 5, 25],
       [ 6, 37]])

In [30]:
z.T.shape # Shape is not a class method. It is a class attribute. Hence why there are no parentheses '()' at the end.

(3, 2)

In [31]:
# See what data type our array is
z.dtype

dtype('int32')

In [32]:
# Cast our array into a different type (in this isntance, float)
z = z.astype('f')
z.dtype

dtype('float32')

## Special Arrays

In [8]:
n = np.arange(0,30,2) # create an 1D array containing 'a range' from 0-30 in increments of 2
print(n)

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28]


In [9]:
n = n.reshape(5,3) # 5 lists, 3 items per list
print(n)

[[ 0  2  4]
 [ 6  8 10]
 [12 14 16]
 [18 20 22]
 [24 26 28]]


In [11]:
o = np.linspace(0, 4, 9) # 9 evenly spaced values from 0-4
print(o)

[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4. ]


In [12]:
o.resize(3,3)
print(o)

[[0.  0.5 1. ]
 [1.5 2.  2.5]
 [3.  3.5 4. ]]


In [13]:
# Create an array of ones
np.ones((3,3)) # <- note, we are inserting a tuple. A list e.g. [3,3] instead of (3,3) would work fine too.

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [14]:
# An array of zeros
np.zeros((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [18]:
# An array with the diagonals as ones
a = np.eye(7) # There are 7 ones in the diagonal
print(a)

[[1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1.]]


In [17]:
# An arrage with a diagonal of our choosing. 
print(np.diag([5,6,7,8,9,10]))

[[ 5  0  0  0  0  0]
 [ 0  6  0  0  0  0]
 [ 0  0  7  0  0  0]
 [ 0  0  0  8  0  0]
 [ 0  0  0  0  9  0]
 [ 0  0  0  0  0 10]]


In [19]:
# An array with a repeating pattern
print(np.array([1,2,3]*2))

[1 2 3 1 2 3]


In [20]:
v = np.repeat([1,2,3],3) 
print(v)
# Again, a tuple would work the same: np.repeat((1,2,3),3) note we can input tuple (1,2,3) instead of list [1,2,3]

[1 1 1 2 2 2 3 3 3]


## Stacking Arrays

In [21]:
# Vertically Stack Arrays
p = np.array([4,5,6]) # To vstack the number of columns in each array must be the same
vstack = np.vstack([p, p*2])
print(vstack)

[[ 4  5  6]
 [ 8 10 12]]


In [22]:
# Horizontally Stack Arrays
hstack = np.hstack([np.diag([1,3,4]), np.eye(3)]) # To hstack the number of rows in each array must be the same
print(hstack)

[[1. 0. 0. 1. 0. 0.]
 [0. 3. 0. 0. 1. 0.]
 [0. 0. 4. 0. 0. 1.]]
